version: '3.5'
services: 
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: isi
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=docker
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  db_volume: